Build as much as possible on non-Linux
gregkh/usbutils pull request #134
Opened 2021-11-21 10:56 UTC by tormodvolden

Disables the Linux-only functionality (udev, sysfs lookups) but otherwise works fairly well on macOS and Windows (MinGW).

I have the suspicion that platform portability is not on the top of the list for usbutils (especially after version 007) but please consider this, or parts of it. Any review and comments are welcome.

This might get into for instance Homebrew https://github.com/Homebrew/homebrew-core/pull/89341, and would be great for cross-platform USB development (e.g. libusb debugging).

2021-11-27 22:59 UTC, ValZapod commented
lsusb was compiled for Windows before.

2022-05-18 19:17 UTC, gregkh commented
Overall, this needs to be made much more maintainable if you want to do this.  Put the #if stuff in .h files and not in the .c files to make this able to be maintained.

Also realize that almost no one will test this, so someone else is going to have to be responsible for handling any breakage or issues reported for that platform.  I can't as I have no access to non-Linux systems, sorry.

2022-05-18 19:19 UTC, gregkh requested changes

2022-05-18 19:19 UTC, gregkh commented on names.c
> +#ifdef HAVE_UDEV
putting #ifdef in .c files like this quickly turns this into a maintance nightmare.

if you really want to do this, put it in a .h file like Linux does, and provide versions with, and without HAVE_UDEV present.  That way the .c code does not care and it is easier to follow and maintain over time.

2022-05-18 19:19 UTC, gregkh commented on usbhid-dump/src/usbhid-dump.c
> +#ifdef HAVE_SIGACTION
Ick, again, put all this in a .h file if you really want to do this properly in a way that can be supported.

And I thought windows supported sigaction already.  That feels like a big missing piece if not.

2022-05-18 19:19 UTC, gregkh commented on sysfs.c
> +#else
again, in a .h file please.

2023-10-11 20:59 UTC, gregkh commented
Closing due to lack of response.

2023-10-11 20:59 UTC, closed without merging