Display (device) power/wakeup via -w option.
gregkh/usbutils pull request #174
Opened 2023-08-16 03:10 UTC by bobhy

Please pardon the unsolicited PR, and feel free to ignore it if you don't like it...  

This change adds an option to `lsusb.py` to display the device power/wakeup setting along with other attributes.  It's triggered by option `-w, --wakeup`, so there is no change by default.

I was troubleshooting my own system suspend/resume behavior (still am!) and found it convenient to see this setting along with the other device attributes.

2023-10-11 18:44 UTC, gregkh requested changes
We need a real changelog text here please.

Also show in the changelog what the new option shows?

2023-10-11 18:44 UTC, gregkh requested changes
This commit shouldn't be needed, and is superseeded by the next one, right?

2023-10-11 18:45 UTC, gregkh requested changes
No need for a merge commit, please rebase?

2023-10-12 05:52 UTC, bobhy commented
ready for review

2023-10-12 12:33 UTC, gregkh approved these changes

2023-10-12 12:33 UTC, merged