Fix usb-utils to work under busybox
gregkh/usbutils pull request #181
Opened 2023-12-12 10:57 UTC by fancsali

The previous implementation relied on the -printf option for find, which is not implemented in BusyBox.

Replaced it with sed to find the basenae of files reliably.

2024-01-04 08:15 UTC, gregkh commented
As the bot says, you need to sign off on your change :(

2024-01-04 08:16 UTC, gregkh requested changes
needs a signed-off-by

2024-01-06 10:43 UTC, fancsali commented
@gregkh, thanks for reminding me.

Just to confirm, what exact meaning do we attach to a commit being signed-off in this project?

2024-01-17 23:21 UTC, fabioestevam commented
> @gregkh, thanks for reminding me.
> 
> Just to confirm, what exact meaning do we attach to a commit being signed-off in this project?

You need to add the following line to your path:

Signed-off-by: Your Name <youremail.com>

See the other commits as references.

2024-01-18 07:00 UTC, gregkh commented
On Wed, Jan 17, 2024 at 03:21:46PM -0800, fabioestevam wrote:
> > @gregkh, thanks for reminding me.
> > 
> > Just to confirm, what exact meaning do we attach to a commit being signed-off in this project?
> 
> You need to add the following line to your path:
> 
> Signed-off-by: Your Name <youremail.com>
> 
> See the other commits as references.

That says what to do, but not what it means :)

This is following the DCO as created by the Linux kernel project, and
I'll document it better later today so as it makes more sense what you
are agreeing to when you add this line of text.

thanks,

greg k-h

2024-02-12 18:06 UTC, fancsali commented
@gregkh, did you, by any chance, get the opportunkty to update the documentation on this, please?

2024-09-01 06:55 UTC, gregkh commented
No, haven't updated the documentation yet, sorry, patches gladly accepted for that as well :)

2024-09-02 17:56 UTC, gregkh commented
Rejecting due to lack of signed-off-by: line :(

2024-09-02 17:56 UTC, closed without merging

2025-12-01 12:40 UTC, fancsali commented
Well, I know I am necro-bumping here, but any developments on this, perhaps? 😉

2025-12-01 12:47 UTC, fabioestevam commented
Hi @fancsali 

Resend your patch with your Signed-off-by if you want it to be considered for inclusion in the project.